# -*- coding: utf-8 -*-
"""TrankitForFRandEng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s775raCHhE-qisMRta5eanIAnQvqFs71
"""

pip install trankit

from trankit import Pipeline

p = Pipeline('french', gpu=False)
# a non-empty string to process, which can be a document or a paragraph with multiple sentences
with open("/Licences_des_entreprises_ferroviaireFR.txt", 'r', encoding='utf-8') as file:
    doc_text = file.read()

all = p(doc_text)
with open('/FRTrankitLicences.txt', 'w', encoding='utf-8') as output_file:
    output_file.write(str(all))